'use strict';
const $=id=>document.getElementById(id),video=$('video'),canvas=$('canvas'),ctx=canvas.getContext('2d');
let clips=[],selected=-1,history=[],busy=false,cancelled=false,audioContext,audioSource,audioGain,audioDestination,recorder;
const sources=new Map();
const fmt=n=>`${String(Math.floor((n||0)/60)).padStart(2,'0')}:${String(Math.floor((n||0)%60)).padStart(2,'0')}`;
const current=()=>clips[selected];
const total=()=>clips.reduce((s,c)=>s+(c.end-c.start)/c.speed,0);
const status=s=>$('status').textContent=s;
function save(){history.push(JSON.stringify({clips,selected}));if(history.length>50)history.shift()}
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000)}
function filter(c){return `brightness(${c.brightness}%) contrast(${c.contrast}%) `+({none:'',mono:'grayscale(1)',warm:'sepia(.35) saturate(1.2)',vivid:'saturate(1.7)'}[c.preset]||'')}
function dimensions(size=720){const [w,h]=$('aspect').value.split(':').map(Number);canvas.width=w>=h?Math.round(size*w/h/2)*2:size;canvas.height=w>=h?size:Math.round(size*h/w/2)*2}
function draw(){const c=current(),w=canvas.width,h=canvas.height;ctx.fillStyle='#050608';ctx.fillRect(0,0,w,h);if(!c||video.readyState<2)return;const scale=Math.min(w/video.videoWidth,h/video.videoHeight),vw=video.videoWidth*scale,vh=video.videoHeight*scale;ctx.save();ctx.filter=filter(c);ctx.drawImage(video,(w-vw)/2,(h-vh)/2,vw,vh);ctx.restore();if(c.title){let fs=Math.round(Math.min(w,h)*.06);ctx.font=`700 ${fs}px system-ui`;while(ctx.measureText(c.title).width>w*.88&&fs>12){fs--;ctx.font=`700 ${fs}px system-ui`}ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillStyle=c.color;ctx.shadowColor='#000';ctx.shadowBlur=8;ctx.fillText(c.title,w/2,c.position==='top'?h*.15:c.position==='center'?h*.5:h*.85);ctx.shadowBlur=0}}
function tick(){draw();if(current()){$('seek').value=video.currentTime;$('time').textContent=fmt(video.currentTime-current().start)+' / '+fmt(current().end-current().start)}requestAnimationFrame(tick)}requestAnimationFrame(tick);
function applyAudio(){const c=current();if(!c)return;video.playbackRate=c.speed;const level=originalMuted?0:c.volume;if(audioGain){audioGain.gain.value=level;video.volume=1}else video.volume=level}
function select(i){if(busy)return;video.pause();selected=i;refresh();if(!current()){video.removeAttribute('src');return}video.src=sources.get(current().source).url;video.load()}
video.addEventListener('loadedmetadata',()=>{if(!busy&&current()){video.currentTime=current().start;applyAudio()}});
video.addEventListener('error',()=>status('This clip cannot be decoded in this browser. Try an MP4 with H.264 video.'));
video.addEventListener('play',()=>{$('play').textContent='❚❚'});video.addEventListener('pause',()=>{$('play').textContent='▶'});
video.addEventListener('timeupdate',()=>{if(!busy&&current()&&video.currentTime>=current().end){video.pause();if(selected<clips.length-1){select(selected+1);video.addEventListener('seeked',()=>video.play().catch(e=>status(e.message)),{once:true})}}});
function refresh(){const c=current();$('empty').hidden=!!c;$('settings').disabled=!c;$('noSelection').hidden=!!c;$('count').textContent=clips.length+' clips';$('length').textContent=fmt(total());$('export').disabled=!clips.length;['play','rewind','seek','split','duplicate','delete','snapshot'].forEach(id=>$(id).disabled=!c);$('undo').disabled=!history.length;$('media').replaceChildren();$('clips').replaceChildren();clips.forEach((clip,i)=>{const b=document.createElement('button');b.className='mediaitem'+(i===selected?' active':'');b.textContent='▣ '+clip.name;b.onclick=()=>select(i);const small=document.createElement('small');small.textContent=fmt((clip.end-clip.start)/clip.speed);b.append(small);$('media').append(b);const card=document.createElement('div');card.className='clip'+(i===selected?' active':'');const pick=b.cloneNode(true);pick.className='select';pick.onclick=()=>select(i);card.append(pick);const order=document.createElement('div');order.className='order';[-1,1].forEach(d=>{const arrow=document.createElement('button');arrow.textContent=d<0?'←':'→';arrow.setAttribute('aria-label',d<0?'Move clip earlier':'Move clip later');arrow.disabled=i+d<0||i+d>=clips.length;arrow.onclick=()=>{save();[clips[i],clips[i+d]]=[clips[i+d],clips[i]];select(i+d)};order.append(arrow)});card.append(order);$('clips').append(card)});if(c){for(const k of ['name','speed','volume','preset','brightness','contrast','title','color','position'])$(k).value=c[k];$('in').value=c.start.toFixed(2);$('out').value=c.end.toFixed(2);$('in').max=c.duration;$('out').max=c.duration;$('seek').min=c.start;$('seek').max=c.end}}
async function importFiles(files){if(busy)return;for(const file of files){if(!file.type.startsWith('video/')){status('Skipped non-video file: '+file.name);continue}const url=URL.createObjectURL(file),probe=document.createElement('video');probe.preload='metadata';try{await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('Metadata loading timed out')),15000);probe.onloadedmetadata=()=>{clearTimeout(timer);resolve()};probe.onerror=()=>{clearTimeout(timer);reject(new Error('Unsupported video'))};probe.src=url});if(!Number.isFinite(probe.duration)||probe.duration<=0)throw new Error('Invalid duration');save();const source=crypto.randomUUID();sources.set(source,{file,url});clips.push({source,name:file.name,duration:probe.duration,start:0,end:probe.duration,speed:1,volume:1,preset:'none',brightness:100,contrast:100,title:'',color:'#ffffff',position:'bottom'});select(clips.length-1);status('Imported '+file.name)}catch(e){URL.revokeObjectURL(url);status(file.name+': '+e.message)}finally{probe.removeAttribute('src');probe.load()}}}
$('import').onclick=$('start').onclick=()=>$('files').click();$('files').onchange=e=>{importFiles([...e.target.files]);e.target.value=''};document.addEventListener('dragover',e=>e.preventDefault());document.addEventListener('drop',e=>{e.preventDefault();importFiles([...e.dataTransfer.files])});
for(const key of ['name','speed','volume','preset','brightness','contrast','title','color','position'])$(key).addEventListener('change',e=>{if(!current()||busy)return;save();current()[key]=['speed','volume','brightness','contrast'].includes(key)?Number(e.target.value):e.target.value;applyAudio();refresh()});
for(const key of ['in','out'])$(key).onchange=()=>{const c=current();if(!c||busy)return;const a=Number($('in').value),b=Number($('out').value);if(!Number.isFinite(a)||!Number.isFinite(b)||a<0||b>c.duration||b-a<.05){status('Choose an in/out range inside the clip, at least 0.05 seconds long.');refresh();return}save();c.start=a;c.end=b;video.currentTime=a;refresh()};
async function play(){if(!current()||busy)return;if(video.paused){if(video.currentTime>=current().end||video.currentTime<current().start)video.currentTime=current().start;try{await ensureAudio();await video.play()}catch(e){status(e.message)}}else video.pause()}
$('play').onclick=play;$('rewind').onclick=()=>{video.currentTime=current().start};$('seek').oninput=e=>{video.currentTime=Number(e.target.value)};
$('split').onclick=()=>{const c=current(),t=video.currentTime;if(!c||t-c.start<.05||c.end-t<.05){status('Move the playhead inside the clip to split it.');return}save();clips.splice(selected,1,{...c,end:t},{...c,start:t});select(selected+1);status('Clip split at '+fmt(t))};$('duplicate').onclick=()=>{if(!current())return;save();clips.splice(selected+1,0,{...current()});select(selected+1)};$('delete').onclick=()=>{if(!current())return;save();clips.splice(selected,1);select(Math.min(selected,clips.length-1))};$('undo').onclick=()=>{if(!history.length||busy)return;const state=JSON.parse(history.pop());clips=state.clips;select(state.selected);status('Undid last edit.')};$('aspect').onchange=()=>dimensions();$('snapshot').onclick=()=>canvas.toBlob(blob=>blob&&download(blob,'cutline-frame.png'));
document.addEventListener('keydown',e=>{if(busy||['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName)||$('exportDialog').open)return;if(e.code==='Space'){e.preventDefault();play()}if(e.key.toLowerCase()==='s')$('split').click();if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();$('undo').click()}});
$('export').onclick=()=>{video.pause();$('exportDialog').showModal()};$('original').onclick=()=>{const s=sources.get(current().source);download(s.file,s.file.name)};
$('cancel').onclick=()=>{cancelled=true};$('exportDialog').addEventListener('cancel',e=>{if(busy){e.preventDefault();cancelled=true}});$('exportDialog').querySelector('form').onsubmit=e=>{if(busy){e.preventDefault();cancelled=true}};document.addEventListener('visibilitychange',()=>{if(busy&&document.hidden){cancelled=true;$('exportStatus').textContent='Export cancelled because the tab was hidden. Keep it visible for reliable rendering.'}});
function waitEvent(target,event,action){return new Promise((resolve,reject)=>{const cleanup=()=>{clearTimeout(timer);target.removeEventListener(event,ok);target.removeEventListener('error',bad)};const ok=()=>{cleanup();resolve()};const bad=()=>{cleanup();reject(new Error('Video could not load'))};const timer=setTimeout(()=>{cleanup();reject(new Error('Video loading timed out'))},15000);target.addEventListener(event,ok,{once:true});target.addEventListener('error',bad,{once:true});action()})}
async function render(){if(busy||!clips.length)return;if(!window.MediaRecorder||!canvas.captureStream){$('exportStatus').textContent='Edited export is unavailable in this browser. You can still download the original.';return}const mime=['video/webm;codecs=vp8,opus','video/webm','video/mp4'].find(t=>MediaRecorder.isTypeSupported(t));if(!mime){$('exportStatus').textContent='No supported recording format. Try Chrome or Edge.';return}busy=true;cancelled=false;document.body.classList.add('busy');$('render').disabled=true;$('original').disabled=true;$('cancel').disabled=false;const oldSelected=selected,oldTime=video.currentTime;let stream,chunks=[],finished=0;try{await ensureAudio();dimensions(Number($('resolution').value));stream=canvas.captureStream(30);for(const track of audioDestination.stream.getAudioTracks())stream.addTrack(track.clone());recorder=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:Number($('quality').value)});recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};const stopped=new Promise((resolve,reject)=>{recorder.onstop=resolve;recorder.onerror=()=>reject(new Error('Encoder failed'))});for(let i=0;i<clips.length;i++){if(cancelled)break;selected=i;const c=current();video.pause();await waitEvent(video,'loadeddata',()=>{video.src=sources.get(c.source).url;video.load()});if(Math.abs(video.currentTime-c.start)>.001)await waitEvent(video,'seeked',()=>{video.currentTime=c.start});applyAudio();draw();if(i===0)recorder.start(250);else recorder.resume();await video.play();await new Promise((resolve,reject)=>{let last=video.currentTime,stamp=Date.now();const check=()=>{if(video.currentTime!==last){last=video.currentTime;stamp=Date.now()}if(cancelled||video.currentTime>=c.end||video.ended){resolve();return}if(video.error||Date.now()-stamp>15000){reject(new Error('Playback stalled. Try a smaller clip or another format.'));return}$('progress').value=(finished+(video.currentTime-c.start)/c.speed)/total()*100;$('exportStatus').textContent='Rendering clip '+(i+1)+' of '+clips.length+' · '+Math.round($('progress').value)+'%';setTimeout(check,20)};check()});video.pause();recorder.pause();finished+=(c.end-c.start)/c.speed}recorder.stop();await stopped;if(cancelled){$('exportStatus').textContent='Export cancelled. No file downloaded.'}else{download(new Blob(chunks,{type:mime}),'cutline-movie.'+(mime.includes('mp4')?'mp4':'webm'));$('progress').value=100;$('exportStatus').textContent='Movie exported. Your download is ready.'}}catch(e){$('exportStatus').textContent='Export failed: '+e.message}finally{video.pause();stopMusic();if(recorder&&recorder.state!=='inactive')recorder.stop();if(stream)stream.getTracks().forEach(t=>t.stop());busy=false;document.body.classList.remove('busy');$('render').disabled=false;$('original').disabled=false;$('cancel').disabled=true;dimensions();select(oldSelected);video.addEventListener('loadeddata',()=>{video.currentTime=oldTime},{once:true})}}
$('render').onclick=render;dimensions();refresh();
