"use client";

import { ChangeEvent, useEffect, useRef, useState } from "react";
import { Clapperboard, Download, Film, Gauge, Pause, Play, RotateCcw, Scissors, SkipBack, SkipForward, Sparkles, Upload, Volume2 } from "lucide-react";

const fmt = (n:number) => !Number.isFinite(n) ? "00:00.0" : `${String(Math.floor(n/60)).padStart(2,"0")}:${(n%60).toFixed(1).padStart(4,"0")}`;

export default function Home() {
  const videoRef=useRef<HTMLVideoElement>(null), inputRef=useRef<HTMLInputElement>(null);
  const [src,setSrc]=useState(""), [fileName,setFileName]=useState("No clip loaded"), [duration,setDuration]=useState(0), [current,setCurrent]=useState(0), [trimStart,setTrimStart]=useState(0), [trimEnd,setTrimEnd]=useState(0), [playing,setPlaying]=useState(false), [volume,setVolume]=useState(1), [speed,setSpeed]=useState(1), [exporting,setExporting]=useState(false), [notice,setNotice]=useState("Import a video to begin editing");
  useEffect(()=>()=>{if(src.startsWith("blob:"))URL.revokeObjectURL(src)},[src]);
  const importFile=(e:ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;if(src.startsWith("blob:"))URL.revokeObjectURL(src);setSrc(URL.createObjectURL(f));setFileName(f.name);setNotice("Clip ready — drag the trim handles to shape your cut")};
  const seek=(n:number)=>{const v=Math.max(0,Math.min(duration,n));if(videoRef.current)videoRef.current.currentTime=v;setCurrent(v)};
  const toggle=async()=>{const v=videoRef.current;if(!v)return;if(v.paused){if(v.currentTime<trimStart||v.currentTime>=trimEnd)seek(trimStart);await v.play()}else v.pause()};
  const exportClip=async()=>{const v=videoRef.current as (HTMLVideoElement&{captureStream?:()=>MediaStream})|null;if(!v?.captureStream||!src){setNotice("WebM export needs a Chromium-based browser");return}setExporting(true);setNotice("Exporting selection in real time…");const old=v.currentTime;try{v.pause();v.currentTime=trimStart;await new Promise<void>(r=>v.addEventListener("seeked",()=>r(),{once:true}));const type=MediaRecorder.isTypeSupported("video/webm;codecs=vp9,opus")?"video/webm;codecs=vp9,opus":"video/webm", rec=new MediaRecorder(v.captureStream(),{mimeType:type}),chunks:BlobPart[]=[];rec.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};const done=new Promise<void>(r=>rec.onstop=()=>r());rec.start(250);await v.play();await new Promise<void>(r=>{const watch=()=>v.currentTime>=trimEnd||v.ended?r():requestAnimationFrame(watch);watch()});v.pause();rec.stop();await done;const url=URL.createObjectURL(new Blob(chunks,{type})),a=document.createElement("a");a.href=url;a.download=`${fileName.replace(/\.[^.]+$/,"")||"cutline"}-trimmed.webm`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice("Export complete — your trimmed clip was downloaded")}catch{setNotice("Export could not finish. Try a shorter selection.")}finally{seek(old);setExporting(false)}};
  const left=duration?trimStart/duration*100:0,width=duration?(trimEnd-trimStart)/duration*100:100,head=duration?current/duration*100:0;
  const tools=[[Film,"Media"],[Scissors,"Trim"],[Sparkles,"Effects"]] as const;
  return <main className="min-h-screen bg-[#090a0c] text-[#f6f4ef]">
    <header className="flex h-16 items-center justify-between border-b border-white/10 px-4 sm:px-6"><div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-xl bg-[#ff6542] text-black"><Clapperboard size={19}/></div><div><h1 className="text-base font-bold">Cutline</h1><p className="text-xs text-white/45">Browser video editor</p></div></div><button onClick={exportClip} disabled={!src||exporting} className="flex min-h-10 items-center gap-2 rounded-xl bg-[#f6f4ef] px-4 text-sm font-bold text-black hover:bg-white disabled:cursor-not-allowed disabled:opacity-35"><Download size={16}/>{exporting?"Exporting…":"Export clip"}</button></header>
    <section className="grid min-h-[calc(100vh-4rem)] grid-cols-1 lg:grid-cols-[88px_minmax(0,1fr)_300px]">
      <nav className="order-2 flex border-t border-white/10 bg-[#0d0f12] lg:order-none lg:flex-col lg:border-r lg:border-t-0">{tools.map(([Icon,label],i)=><button key={label} className={`flex min-h-16 flex-1 flex-col items-center justify-center gap-1 text-xs lg:flex-none ${i===0?"bg-white/[.06] text-[#ff8065]":"text-white/45 hover:text-white"}`}><Icon size={19}/><span>{label}</span></button>)}</nav>
      <div className="flex min-w-0 flex-col">
        <div className="flex min-h-[430px] flex-1 items-center justify-center bg-[radial-gradient(circle_at_center,#24272c_0,#111318_52%,#090a0c_100%)] p-5 sm:p-8">{src?<video ref={videoRef} src={src} onLoadedMetadata={()=>{const d=videoRef.current?.duration||0;setDuration(d);setTrimStart(0);setTrimEnd(d);setCurrent(0)}} onTimeUpdate={e=>{const t=e.currentTarget.currentTime;setCurrent(t);if(t>=trimEnd){e.currentTarget.pause();setPlaying(false)}}} onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} className="max-h-[58vh] w-full max-w-5xl rounded-md bg-black shadow-2xl" playsInline/>:<button onClick={()=>inputRef.current?.click()} className="group flex min-h-64 w-full max-w-2xl flex-col items-center justify-center rounded-2xl border border-dashed border-white/20 bg-white/[.025] px-8 hover:border-[#ff6542]/70"><span className="mb-5 grid h-16 w-16 place-items-center rounded-2xl bg-[#ff6542]/15 text-[#ff8065]"><Upload size={26}/></span><span className="text-lg font-bold">Drop a video here</span><span className="mt-2 text-sm text-white/45">or click to choose a file from your device</span></button>}</div>
        <div className="border-t border-white/10 bg-[#101216] p-4 sm:p-5"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2"><button disabled={!src} onClick={()=>seek(trimStart)} className="control"><SkipBack size={18}/></button><button disabled={!src} onClick={toggle} className="grid h-11 w-11 place-items-center rounded-full bg-[#ff6542] text-black hover:bg-[#ff8065] disabled:opacity-30">{playing?<Pause size={20} fill="currentColor"/>:<Play size={20} fill="currentColor"/>}</button><button disabled={!src} onClick={()=>seek(Math.min(trimEnd,current+5))} className="control"><SkipForward size={18}/></button></div><div className="rounded-lg bg-black/30 px-3 py-2 font-mono text-sm"><span>{fmt(current)}</span><span className="text-white/30"> / {fmt(duration)}</span></div><button disabled={!src} onClick={()=>{setTrimStart(0);setTrimEnd(duration);setNotice("Trim reset to the full clip")}} className="flex items-center gap-2 text-sm text-white/50 hover:text-white disabled:opacity-30"><RotateCcw size={15}/>Reset trim</button></div>
          <div className="relative h-24 overflow-hidden rounded-xl border border-white/10 bg-[#191c21]"><div className="absolute inset-0 flex items-center gap-1 px-2 opacity-40">{Array.from({length:36}).map((_,i)=><span key={i} className="h-12 flex-1 rounded-sm bg-gradient-to-b from-[#a9b8c8] to-[#46515e]" style={{opacity:.35+(i%6)*.1}}/>)}</div><div className="absolute inset-y-0 border-x-2 border-[#ff6542] bg-[#ff6542]/10" style={{left:`${left}%`,width:`${width}%`}}/><div className="pointer-events-none absolute inset-y-0 w-px bg-white shadow-[0_0_8px_white]" style={{left:`${head}%`}}><span className="absolute -left-1.5 top-0 h-3 w-3 rotate-45 bg-white"/></div><input aria-label="Playhead" disabled={!src} type="range" min={0} max={duration||1} step=".05" value={current} onChange={e=>seek(Number(e.target.value))} className="absolute inset-0 z-10 h-full w-full cursor-col-resize opacity-0"/></div>
          <div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="range-label"><span>In <b>{fmt(trimStart)}</b></span><input disabled={!src} type="range" min={0} max={duration||1} step=".05" value={trimStart} onChange={e=>{const n=Math.min(Number(e.target.value),trimEnd-.1);setTrimStart(n);seek(n)}}/></label><label className="range-label"><span>Out <b>{fmt(trimEnd)}</b></span><input disabled={!src} type="range" min={0} max={duration||1} step=".05" value={trimEnd} onChange={e=>setTrimEnd(Math.max(Number(e.target.value),trimStart+.1))}/></label></div></div>
      </div>
      <aside className="border-l border-white/10 bg-[#0d0f12] p-5 max-lg:hidden"><p className="mb-2 text-xs font-bold uppercase tracking-[.16em] text-white/35">Media</p><button onClick={()=>inputRef.current?.click()} className="flex min-h-11 w-full items-center justify-center gap-2 rounded-xl border border-white/12 bg-white/[.04] text-sm font-semibold hover:bg-white/[.08]"><Upload size={16}/>Import video</button><div className="mt-4 rounded-xl border border-white/10 bg-white/[.025] p-4"><div className="mb-3 flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-lg bg-[#ff6542]/15 text-[#ff8065]"><Film size={18}/></div><div className="min-w-0"><p className="truncate text-sm font-semibold">{fileName}</p><p className="text-xs text-white/35">{duration?`${fmt(duration)} duration`:"MP4, WebM, MOV"}</p></div></div><p className="text-xs leading-5 text-white/40">{notice}</p></div><div className="mt-7 space-y-6"><p className="text-xs font-bold uppercase tracking-[.16em] text-white/35">Clip controls</p><label className="range-label"><span><i className="flex items-center gap-2 not-italic"><Volume2 size={15}/>Volume</i><b>{Math.round(volume*100)}%</b></span><input type="range" min="0" max="1" step=".01" value={volume} onChange={e=>{const n=Number(e.target.value);setVolume(n);if(videoRef.current)videoRef.current.volume=n}}/></label><label className="range-label"><span><i className="flex items-center gap-2 not-italic"><Gauge size={15}/>Speed</i><b>{speed}×</b></span><input type="range" min=".5" max="2" step=".25" value={speed} onChange={e=>{const n=Number(e.target.value);setSpeed(n);if(videoRef.current)videoRef.current.playbackRate=n}}/></label></div><div className="mt-8 rounded-xl bg-[#ff6542]/10 p-4 text-sm text-[#ffb09e]"><div className="mb-1 flex items-center gap-2 font-bold"><Scissors size={15}/>Selection</div><p className="text-xs leading-5 text-white/45">{fmt(Math.max(0,trimEnd-trimStart))} will be exported as a WebM clip.</p></div></aside>
    </section><input ref={inputRef} className="hidden" type="file" accept="video/*" onChange={importFile}/>
  </main>
}
